procs:
  rosbag:
    shell: 'bash -c "sleep 1 && source ~/workspaces/s_graphs/install/setup.bash && ros2 bag play ~/Downloads/virtual/stugalux_oetrange_f2_3r.db3"'
    autostart: true
    stop: SIGINT
  s_graphs:
    shell: 'bash -c "source ~/workspaces/s_graphs/install/setup.bash && ros2 launch lidar_situational_graphs s_graphs_launch.py compute_odom:=true base_link_frame:=base_footprint"'
    autostart: true
  rviz:
    shell: 'bash -c "source ~/workspaces/s_graphs/install/setup.bash && rviz2 -d ~/workspaces/s_graphs/s_graphs/rviz/s_graphs_ros2.rviz"'
    autostart: true
