name: ROS 2 Foxy

on:
  push:
    branches: 
      - "feature/ros2"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:foxy
    steps:
      - name: Create Workspace
        run: mkdir -p $HOME/workspaces/s_graphs_ros2_ws/src     
     
      - name: Checkout code
        run: cd $HOME/workspaces/s_graphs_ros2_ws/src && . /opt/ros/foxy/setup.sh  && git clone https://github.com/snt-arg/s_graphs.git
      
      - name: Build
        run: . /opt/ros/foxy/setup.sh && ./setup.sh