name: ROS 2 Foxy

on:
  push:
    branches:
      - feature/ros2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:foxy
    steps:
      - name: Create Workspace and checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: . /opt/ros/foxy/setup.sh && ./.github/workflows/setup.sh && colcon build