name: ROS 2 Humble

on:
  push:
    branches:
      - feature/ros2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Create Workspace and checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          . /opt/ros/humble/setup.sh && \
          mkdir -p $HOME/workspace/s_graphs_ws/src && \
          cd .. && \
          cp -r s_graphs $HOME/workspace/s_graphs_ws/src && \
          cd $HOME/workspace/s_graphs_ws/src/s_graphs && \
          ./.github/workflows/setup.sh && \
          cd ../../ && colcon build --symlink-install