name: ROS 2 Humble

on:
  push:
    branches:
      - feature/ros2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:humble
    steps:
      - name: Create Workspace
        run: mkdir -p $HOME/workspaces/s_graphs_ros2_ws/src && cd $HOME/workspaces/s_graphs_ros2_ws/src && source /opt/ros/humble/setup.bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: ./setup.sh
