name: ROS 2 Iron

on:
  push:
    branches:
     - feature/ros2

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sntarg/unitree_ros:iron
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: ./setup.sh && colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
